In [7]:
import sqlite3
from sqlite3 import Error
import pandas as pd


def db_build():
    
    database = r"C:\Users\arbis\Projects\nate_silver_gets_me_money\dk_538_games.db" 
    
    team_df = pd.read_csv("C:/Users/arbis/Projects/nate_silver_gets_me_money/team.csv")
    
    conn = None
    try:
        conn = sqlite3.connect(database)
    except Error as e:
        print(e)
    
#     conn = create_connection(database)

    sql_drop_team = """ DROP TABLE IF EXISTS team;"""
    sql_drop_predict_538 = """DROP TABLE IF EXISTS predictions_538;"""
    sql_drop_ml_dk = """DROP TABLE IF EXISTS moneylines_dk;"""
    
    sql_create_team_query = """ CREATE TABLE IF NOT EXISTS team (
                                        team_id int,
                                        team_name text,
                                        team_abr text,
                                        PRIMARY KEY (team_id)
                                    ); """
    
    sql_create_dk_table_query = """ CREATE TABLE IF NOT EXISTS moneylines_dk (
                                        game_date text,
                                        away_team int,
                                        home_team int,
                                        away_ml_dk int NOT NULL,
                                        home_ml_dk int NOT NULL,
                                        PRIMARY KEY (game_date, away_team, home_team)
                                        FOREIGN KEY (away_team)
                                            REFERENCES team (team_id) 
                                        FOREIGN KEY (home_team)
                                            REFERENCES team (team_id) 
                                    ); """

    sql_create_538_table_query = """ CREATE TABLE IF NOT EXISTS predictions_538 (
                                        game_date text,
                                        away_team int,
                                        home_team int,
                                        away_pct_538 float NOT NULL,
                                        home_pct_538 float NOT NULL,
                                        PRIMARY KEY (game_date, away_team, home_team)
                                        FOREIGN KEY (away_team)
                                            REFERENCES team (team_id) 
                                        FOREIGN KEY (home_team)
                                            REFERENCES team (team_id)                                        
                                    ); """   
    if conn is not None:
        
        ## Drop the tables
        try:
            c = conn.cursor()
            c.execute(sql_drop_predict_538)
            c.execute(sql_drop_ml_dk)
            c.execute(sql_drop_team)

        except Error as e:
            print(e)
               
        ## create the tables
        try:   
            c.execute(sql_create_team_query)
            c.execute(sql_create_dk_table_query)
            c.execute(sql_create_538_table_query)
        except Error as e:
            print(e)
            

    else:
        print("Error! cannot create the database connection.")

    c.close()                         
        
    ## finally, we add the team_table
    team_df.to_sql("team", conn, if_exists='append', index=False)

    conn.close()

In [8]:
db_build()

### Doublechecking that the team table loaded properly

In [9]:
conn = None
try:
    conn = sqlite3.connect(r"C:\Users\arbis\Projects\nate_silver_gets_me_money\dk_538_games.db" )
except Error as e:
    print(e)
cur = conn.cursor()
cur.execute("SELECT * FROM team")

rows = cur.fetchall()
cur.close() 
conn.close()

for row in rows:
    print(row)

(1, 'Diamondbacks', 'ARI')
(2, 'Braves', 'ATL')
(3, 'Orioles', 'BAL')
(4, 'Red Sox', 'BOS')
(5, 'Cubs', 'CHC')
(6, 'White Sox', 'CHW')
(7, 'Reds', 'CIN')
(8, 'Indians', 'CLE')
(9, 'Rockies', 'COL')
(10, 'Tigers', 'DET')
(11, 'Marlins', 'MIA')
(12, 'Astros', 'HOU')
(13, 'Royals', 'KCR')
(14, 'Angels', 'LAA')
(15, 'Dodgers', 'LAD')
(16, 'Brewers', 'MIL')
(17, 'Twins', 'MIN')
(18, 'Mets', 'NYM')
(19, 'Yankees', 'NYY')
(20, 'Athletics', 'OAK')
(21, 'Phillies', 'PHI')
(22, 'Pirates', 'PIT')
(23, 'Padres', 'SDP')
(24, 'Giants', 'SFG')
(25, 'Mariners', 'SEA')
(26, 'Cardinals', 'STL')
(27, 'Rays', 'TBR')
(28, 'Rangers', 'TEX')
(29, 'Blue Jays', 'TOR')
(30, 'Nationals', 'WSH')